server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 831121

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiguiquan.springcloud.entities  #所有entity别名所在包
