server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 831121

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka # 单机版 入驻的EurekaServer地址
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  #集群版
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiguiquan.springcloud.entities  #所有entity别名所在包